### ISSUE TITLE
not giving the output

### ISSUE THREAD

**Issue by soniyakamble11** [hankareriya/emergency-service-project#10]
Traceback (most recent call last):
  File "/home/soniya/tom.py", line 3, in <module>
    from PIL import Image, ImageTk
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

**Comment by hankareriya** [comment]
you need to install package Pillow on your pc 
command - apt install pillow
