### ISSUE TITLE
there is an issue in assign6.sh

### ISSUE THREAD

**Issue by dev1804** [hankareriya/emergency-service-project#9]
the output for the star pattern in circle shape is not occuring
<img width="960" alt="8 1" src="https://github.com/user-attachments/assets/ea06566e-147e-4101-ae0d-0a7d5d683ff8">
<img width="960" alt="image" src="https://github.com/user-attachments/assets/e5e5fea9-c1b1-4377-b948-b0929b4a4c4f">
DELL@DESKTOP-GOVEEHJ MINGW64 ~/OneDrive/Desktop/college/SEM V/SE LAB
$ assign6.sh
bash: assign6.sh: command not found

DELL@DESKTOP-GOVEEHJ MINGW64 ~/OneDrive/Desktop/college/SEM V/SE LAB
$ bash assign6.sh
Choose an option:
1. Star Pattern in STAR Shape
2. Star Pattern in CIRCLE Shape
Enter your choice: 2
Enter the width (odd number for star pattern): 10
Star Pattern in CIRCLE Shape
*

**Comment by Anu1122004** [comment]
correct code for this issue- select large radius

#!/bin/bash
echo "Enter the radius of circle:"
read radius  #grid (radius *radius)


for ((i=-radius; i<=radius; i++)); do #rows
    for ((j=-radius; j<=radius; j++)); do #column
        distance=$((i*i + j*j))
        if (( distance <= radius*radius )); then
            echo -n "*"
        else
            echo -n " "
        fi
    done
    echo
done

output is-
![Screenshot 2024-10-10 154021](https://github.com/user-attachments/assets/442ed237-72ea-431e-ac8b-5fff8a82ff7b)
